### ISSUE TITLE
yolov8n-seg.onnx推理时间问题为什么慢这么多？

### ISSUE THREAD

**Issue by ZhuJD-China** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#1]
image:  bus.jpg
C++ onnxruntime GPU
_OrtSession->Run Time : 87.000000ms
_OrtSession->Run Time : 84.000000ms
_OrtSession->Run Time : 86.000000ms
_OrtSession->Run Time : 99.000000ms
_OrtSession->Run Time : 89.000000ms
_OrtSession->Run Time : 86.000000ms

python pytorch-gpu yolov8n-seg.pt
Speed: 1.0ms pre-process, 17.0ms inference, 9.0ms postprocess per image at shape (1, 3, 640, 640)

**Comment by UNeedCryDear** [comment]
我没问题啊，而且我这是动态模型推理速度都正常的。你开任务管理器看下你的显卡显存有无上升，然后看下cuda有没有上升，应该是你没有调用到显卡的问题。
![20230207230517](https://user-images.githubusercontent.com/52729998/217282235-fe1537d1-ea0e-4990-8eb3-8ca879b88d77.png)
