### ISSUE TITLE
where can I find the onnx model

### ISSUE THREAD

**Issue by ReverseSystem001** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#10]
https://github.com/ultralytics/ultralytics
It seems like that the link only has pth models

**Comment by UNeedCryDear** [comment]
export onnx-file by your self!
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/7f5b53a4-99ba-4d6c-9ea7-cbf17e5fdbc8)
