### ISSUE TITLE
严重性	代码	说明	项目	文件	行	禁止显示状态 错误	LNK2019	无法解析的外部符号 OrtSessionOptionsAppendExecutionProvider_CUDA，函数 "public: bool __cdecl Yolov8Onnx::ReadModel(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool,int,bool)" (?ReadModel@Yolov8Onnx@@QEAA_NAEBV?

### ISSUE THREAD

**Issue by Bob-jpg** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#11]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 OrtSessionOptionsAppendExecutionProvider_CUDA，函数 "public: bool __cdecl Yolov8Onnx::ReadModel(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool,int,bool)" (?ReadModel@Yolov8Onnx@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_NH1@Z) 中引用了该符号	yololite2	C:\Users\admin\source\repos\yololite2\yololite2\12.obj	1

**Comment by Bob-jpg** [comment]
我用博主你的代码读取模型出现了这个问题

**Comment by UNeedCryDear** [comment]
ort版本多少

**Comment by Bob-jpg** [comment]
1.12

**Comment by Bob-jpg** [comment]
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/56429665/d214fe0a-bcf7-4622-a344-07a3afddfeed)

**Comment by UNeedCryDear** [comment]
这里改成13看下呢
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/yolov8_utils.h#L7

**Comment by Bob-jpg** [comment]
> 这里改成13看下呢
> 
> https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/yolov8_utils.h#L7

yolov8可以了，但我测试yololite的时候没有输出检测框，大佬

**Comment by edwardzxw** [comment]
虽然 你用的是YoloLite，但是你的问题可能是因为没有添加Microsoft.ML.OnnxRuntime.Gpu的nuget依赖导致的。

我在本地试着编译这个项目的时候也遇到类似的问题，当时通过添加Microsoft.ML.OnnxRuntime.Gpu依赖可以解决。
