### ISSUE TITLE
请问yolo8是否考虑了图像长宽相差很大的情况

### ISSUE THREAD

**Issue by SuperGentry** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#13]
博主你好，比如有一张760x200的图片，把图片大小变为640x640输入模型推理的时候会不会出现预测内容偏移的情况？
或者说，有没有必要先把图像大小提前填充为760x760的大小，然后再等比例放缩？

**Comment by UNeedCryDear** [comment]
代码里面会自动按照python源码的做法处理的，也就是先将长边resize到640，然后短边填充指定像素到640
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/yolov8_utils.cpp#L14
