### ISSUE TITLE
是否可以batch预测

### ISSUE THREAD

**Issue by panbo-bridge** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#15]
您好，支持batch批量预测吗？

**Comment by panbo-bridge** [comment]
好的，谢谢！有测试过yolov8s-seg分别使用opencv::dnn和onnruntime加载的推理时间吗？我使用opencv::dnn处理一张需要1300ms，不知道是不是正常的？

**Comment by UNeedCryDear** [comment]
没有很仔细测试。不过计算时间一般不会算加载模型的时间，比较大多数情况下模型只会加载一次。如果只有推理时间，cpu推理1.3s，你这个速度都有点慢了，我不知道你怎么弄的还是你的cpu不行，我cpu推理差不多在200-300ms之间，上gpu，640x640可以达到15~30ms左右，如果onnxruntime的话，还会快一些，如果想要追求极致速度，还是得tensorRT。
