### ISSUE TITLE
opencv4.4影响吗？

### ISSUE THREAD

**Issue by hankhhy** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#16]
你好，因为我需要在vs2015中配置，需要vc14，opencv编译好的最高版本是opencv4.4，我想请问一下opencv4.5与opencv4.4的区别？对这个代码有什么影响？

**Comment by UNeedCryDear** [comment]
如果你跑的是onnxruntime，那么opencv版本影响不大，3.x的版本改个api接口就能用。但是如果你想用opencv推理的话，那就不行了，这个时候opencv版本至少要高于4.7
