### ISSUE TITLE
batch推理时候代码需要改那些地方

### ISSUE THREAD

**Issue by panbo-bridge** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#17]
我想使用batch来推理，我需要修改数据输入的格式，输出的处理逻辑吗？

**Comment by UNeedCryDear** [comment]
opencv的话要改动一些，onnxruntime的话直接调用batc的接口即可
检测调用这个
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/yolov8_onnx.cpp#L179C18-L179C33
分割调用这个
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/yolov8_seg_onnx.cpp#L207

**Comment by panbo-bridge** [comment]
我使用onnxruntime batch推理时候，这行代码报异常了mask = mask(temp_rect - Point(left, top)) > mask_threshold;

**Comment by UNeedCryDear** [comment]
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/issues/17#issuecomment-1711370848

**Comment by panbo-bridge** [comment]
output类型要改吗？我看直接注释取消了编译会报错

**Comment by panbo-bridge** [comment]
![1694166711930_4957E13C-3B92-479f-A5FE-D154A35FB26E](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/73381110/6e7b8e02-b9f1-438d-bb87-8ec30e1479f6)

**Comment by UNeedCryDear** [comment]
换成temp_output啊，你cpp是一点都不会吗，类型不对

**Comment by panbo-bridge** [comment]
我刚接触cpp，现在可以跑了，之前报错是模型没有设置dynamic=True。感谢感谢！
