### ISSUE TITLE
感谢作者的工作，有一个问题想要请教一下！

### ISSUE THREAD

**Issue by Jaxys10** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#18]
当我用opencv调用yolov8模型时，cpu运行能够推理出结果且不报错下x,y,w,h有值，但当我使用cuda推理虽然不报错，但其中的x,y,w,h值为0但是max_class_socre却有值完全没有框的信息。这是为什么呢？想要使用cuda推理，cpu推理有点缓慢。

**Comment by UNeedCryDear** [comment]
应该是opencv的问题，你的opencv版本多少，编译的cuda是否有正确编译。
如果要调用cuda的话，我还是比较建议走onnxruntime，直接使用不需要编译，只要你有cuda环境即可

**Comment by Jaxys10** [comment]
谢谢作者回复，我的opencv版本是4.8.0，我发现在yolov8和opencv的官方issue里面也有人提出了这个问题，暂时还不知道什么原因，也有可能是cuda版本问题。我打算尝试一下onnxruntime！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月10日 02:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [UNeedCryDear/yolov8-opencv-onnxruntime-cpp] 感谢作者的工作，有一个问题想要请教一下！ (Issue #18) |

应该是opencv的问题，你的opencv版本多少，编译的cuda是否有正确编译。
如果要调用cuda的话，我还是比较建议走onnxruntime，直接使用不需要编译，只要你有cuda环境即可

**Comment by Li-Yidong** [comment]
> 谢谢作者回复，我的opencv版本是4.8.0，我发现在yolov8和opencv的官方issue里面也有人提出了这个问题，暂时还不知道什么原因，也有可能是cuda版本问题。我打算尝试一下onnxruntime！
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年09月10日 02:21 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [UNeedCryDear/yolov8-opencv-onnxruntime-cpp] 感谢作者的工作，有一个问题想要请教一下！ (Issue #18) | 应该是opencv的问题，你的opencv版本多少，编译的cuda是否有正确编译。 如果要调用cuda的话，我还是比较建议走onnxruntime，直接使用不需要编译，只要你有cuda环境即可 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你好，我也遇到了同样的问题，请问你用onnxruntime的cuda调试成功了吗

**Comment by Jaxys10** [comment]
用的opencv4.7.0 成功了，应该是4.8.0的bug



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月13日 12:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [UNeedCryDear/yolov8-opencv-onnxruntime-cpp] 感谢作者的工作，有一个问题想要请教一下！ (Issue #18) |

谢谢作者回复，我的opencv版本是4.8.0，我发现在yolov8和opencv的官方issue里面也有人提出了这个问题，暂时还不知道什么原因，也有可能是cuda版本问题。我打算尝试一下onnxruntime！
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年09月10日 02:21 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [UNeedCryDear/yolov8-opencv-onnxruntime-cpp] 感谢作者的工作，有一个问题想要请教一下！ (Issue #18) | 应该是opencv的问题，你的opencv版本多少，编译的cuda是否有正确编译。 如果要调用cuda的话，我还是比较建议走onnxruntime，直接使用不需要编译，只要你有cuda环境即可 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

你好，我也遇到了同样的问题，请问你用onnxruntime的cuda调试成功了吗

**Comment by Li-Yidong** [comment]
> 用的opencv4.7.0 成功了，应该是4.8.0的bug
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年09月13日 12:18 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [UNeedCryDear/yolov8-opencv-onnxruntime-cpp] 感谢作者的工作，有一个问题想要请教一下！ (Issue #18) | 谢谢作者回复，我的opencv版本是4.8.0，我发现在yolov8和opencv的官方issue里面也有人提出了这个问题，暂时还不知道什么原因，也有可能是cuda版本问题。我打算尝试一下onnxruntime！ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年09月10日 02:21 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [UNeedCryDear/yolov8-opencv-onnxruntime-cpp] 感谢作者的工作，有一个问题想要请教一下！ (Issue #18) | 应该是opencv的问题，你的opencv版本多少，编译的cuda是否有正确编译。 如果要调用cuda的话，我还是比较建议走onnxruntime，直接使用不需要编译，只要你有cuda环境即可 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 你好，我也遇到了同样的问题，请问你用onnxruntime的cuda调试成功了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

好的！感谢！那我也去试一下
