### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by EthanAbitbol3** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#19]
Hello and thank you for your work !

I am a newcomer to C++ and I've been attempting to comprehend how to use/compile the code, but I haven't been successful. Could you kindly provide guidance on how to utilize your code? Here's some additional information:
- I've exported the YOLOv8 segmentation weights for a custom dataset to the ONNX format.
- I am running Windows.

Thank you once again for your help!

**Comment by UNeedCryDear** [comment]
use cmake
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/CMakeLists.txt#L5

set opencv and opnnxruntime path.
If you don't know how to use cmake, please Google it. This is no something that can be explained clearly in just a few words, especially since different IDEs have different configuration schemes. I'm not sure what IDE you're using, I can only tell you about the general purpose.

If you are using VS/VScode, please configure the library path and header file path for opencv and onnxruntime in the project properties (this is not difficult, I believe it will be much simpler than the cmake above, as long as you Google VS to configure opencv and onnxruntime), and then add the source code to the project for compilation.

**Comment by UNeedCryDear** [comment]
For example of vs2019:
(I'm sorry I only have Chinese UI)
1. File->new ->progect ->win32 Console Application -> Empty project ->next step
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/b898d0f4-f3ac-4537-8484-244f0dee8f05)

2. set your peoject name and path,and then create project.
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/c89b3633-c07d-493a-82eb-94ff80738d8f)
3. download src code to project,and then add into project.Right-click the source code option and select Add existing item
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/928cbe98-c4b1-47de-9fe5-4c5aa22af03c)
4. change project to x64
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/7af4ad4d-8972-4978-baea-d7f108c53fda)
5. Find the Property-Manager-window in the View
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/c24c4ee8-7fea-47ea-b5c6-0e80cc02a126)
6. Open the X64 properties page and configure the include paths for opencv and onnxruntime.Note that you are using your own path and version number replacements for opencv and onnxruntime
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/806b99e5-22eb-4091-891a-dcf619266ed6)
7. add libliry path，Note that you are using your own path and version number replacements for opencv and onnxruntime
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/6fad9fdb-515a-451e-ad0c-72717d7e265b)
8.Add additional dependencies，include "onnxruntime.lib" and "opencv_worldxxxd.lib",“xxx” is your opencv version
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/20ebb8ca-3dec-49ae-adb7-5cd9e67c8758)
9. When everything is configured, you are ready to run. Just replace the models and images with your own path.
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/main.cpp#L81

**Comment by UNeedCryDear** [comment]
https://github.com/microsoft/onnxruntime/releases/tag/v1.15.1

**Comment by UNeedCryDear** [comment]
If you only want opencv to inference, remove the files with “xxxx_onnx.h/.cpp” characters in the file name from your project, and finally remove the relevant "xxx_onn.h" and classes from the main.cpp

**Comment by UNeedCryDear** [comment]
change [_ClassNames](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/yolov8_seg.h#L41C27-L41C38)  and
[_netWidth/_netHeight/_segW/_segH](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/yolov8_seg.h#L27)
