### ISSUE TITLE
Error loading the model (OpenCV)

### ISSUE THREAD

**Issue by rmsalinas** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#2]
Hi. 
I am trying to use the code with opencv. 
I export the model as
`yolo export model=yolov8n.pt format=onnx`
then, when I load the model using Yolov8::ReadModel, I got the following error message 

[ERROR:0@0.037] global onnx_importer.cpp:1051 handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Reshape]:(onnx_node!/model.22/dfl/Reshape) from domain='ai.onnx'
OpenCV(4.7.0) /home/salinas/Libraries/opencv/opencv-4.7.0/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Reshape@ai.onnx]:(onnx_node!/model.22/dfl/Reshape) parse error: OpenCV(4.7.0) /home/salinas/Libraries/opencv/opencv-4.7.0/modules/dnn/src/layers/reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

However, the model works fine when using the onnx runtime class Yolov8Onnx

Any ideas what I am doing wrong?

Thanks in advance

**Comment by UNeedCryDear** [comment]
Opencv does not support dynamic shape,
try:
```
yolo export model=yolov8n.pt format=onnx dynamic=False
```

**Comment by rmsalinas** [comment]
Hi,
no it does not work.

[ERROR:0@0.036] global onnx_importer.cpp:1051 handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Reshape]:(onnx_node!/model.22/dfl/Reshape) from domain='ai.onnx'
OpenCV(4.7.0) /home/salinas/Libraries/opencv/opencv-4.7.0/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Reshape@ai.onnx]:(onnx_node!/model.22/dfl/Reshape) parse error: OpenCV(4.7.0) /home/salinas/Libraries/opencv/opencv-4.7.0/modules/dnn/src/layers/reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

**Comment by UNeedCryDear** [comment]
use https://netron.app/ to open your model.
![image](https://user-images.githubusercontent.com/52729998/218263251-8858e4d7-d3ff-4f2f-968d-e5d7668e0c86.png)

**Comment by UNeedCryDear** [comment]
> Hi, no it does not work.
> 
> [ERROR:0@0.036] global onnx_importer.cpp:1051 handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Reshape]:(onnx_node!/model.22/dfl/Reshape) from domain='ai.onnx' OpenCV(4.7.0) /home/salinas/Libraries/opencv/opencv-4.7.0/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> 
> > Node [[Reshape@ai.onnx](mailto:Reshape@ai.onnx)]:(onnx_node!/model.22/dfl/Reshape) parse error: OpenCV(4.7.0) /home/salinas/Libraries/opencv/opencv-4.7.0/modules/dnn/src/layers/reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

I forgot to mention that you should set your opset =12 for opencv-dnn.
try:
```python
yolo export model=yolov8n.pt format=onnx dynamic=False opset=12
```

**Comment by rmsalinas** [comment]
You are a genius. Thanks a lot!
