### ISSUE TITLE
yolov8分割_opencv_dnn

### ISSUE THREAD

**Issue by lhehejunl** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#21]
大佬，我用opencv4.7.0 readNet失败，用opencv4.8.0能正常读取，正常输出结果。
我想问，配置完opencv4.7.0真的可以运行吗？还是我用opencv4.7.0时需要注意点啥？
请大佬解惑。

**Comment by UNeedCryDear** [comment]
readNetFromONNX失败还是forward失败？
我之前测试的就是4.7.0可以用啊，难不成最近一段时间的更新之后4.7.0不能用了？如果是无法读取的话，那晚些时间我看下

**Comment by lhehejunl** [comment]
net = readNet(netPath);  这句就抛异常了。还没走到forward

**Comment by UNeedCryDear** [comment]
你如果改成readNetFromONNX()呢？我刚刚测试了下，原来的代码没有问题。你看下是不是torch1.12.x的版本导出的onnx，一般来说这个版本问题会大一些，基本上都不会用

**Comment by UNeedCryDear** [comment]
如果你还是无法确定是什么问题，就请提供一下模型或者onnx文件

**Comment by lhehejunl** [comment]
我刚试了下，改成readNetFromONNX()也不行，我是 torch1.8.0+cu11 导出的onnx。我看看怎么往这上面发模型

**Comment by lhehejunl** [comment]
不知道在这上面怎么上传模型，放在百度网盘行吗？
链接：https://pan.baidu.com/s/1y4peUaBztjJzhX14Jbi0uA 
提取码：1234

**Comment by UNeedCryDear** [comment]
我看了你的模型是可以正确读取的。
另外我修复了运行你模型可能会导致的bug，你可以重新获取下代码看看

**Comment by lhehejunl** [comment]
好的，大佬，我试下。

**Comment by lhehejunl** [comment]
额，遇到一个尴尬的问题，我现在用的这个opencv470版本可能比较早，我又从官网上重新下了个opencv470，配置好后一下就跑通了。- -！
