### ISSUE TITLE
编译报错问题！

### ISSUE THREAD

**Issue by zelohon** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#23]
![UH(YDGROPXHBHZ}Z)MVO_NL](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/36800197/fbe42221-16be-4dca-a0a6-0663405b09fa)
编译会报很多错误  OpenCV路径我都设置好了 我应该怎么办？ 什么地方没弄对？

**Comment by zelohon** [comment]
![OO_U3%I1`$WKW%6D4R90_60](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/36800197/6561a4f2-65c2-4852-acce-83c81cdaf5c0)
处理完之后还有这么多报错！

**Comment by UNeedCryDear** [comment]
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/f077831b-c51e-43a7-bdb6-1df46bce16d2)

你没有修改完全，用到的文件需要全部修改这个换行符

**Comment by zelohon** [comment]
确实 解决了  非常感谢！！

**Comment by zelohon** [comment]
![3)J1316NHQTX)Q{{_~4H W](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/36800197/3e11b7ec-c0f7-4df2-b66e-5f9da6d2bbdd)
我这边又有新编译错误了

**Comment by zelohon** [comment]
![VEIB$0WN7)UK)U@UWZW~UXM](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/36800197/565c3012-b805-4f48-b476-634e13cdfdfb)
这里注释掉可以了  我这样注释掉 会不会有啥影响？

**Comment by UNeedCryDear** [comment]
onnxruntime没有下载GPU版本，调用不了GPU就是了，其他正常用

**Comment by zelohon** [comment]
OK
