### ISSUE TITLE
这代码中会先将onnx转为engine么？

### ISSUE THREAD

**Issue by Lishumuzixin** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#34]
你好，我刚刚了解这个部署，请问这个项目中会先将onnx转为engine么？

**Comment by UNeedCryDear** [comment]
目前项目中不会转出engine，除非你自己将后端从cuda改为tensorRT的后端，这个时候ort会自动生成一个engine文件供给tensorRT的后端来推理使用。
就当前我项目来说，直接就是onnx的文件，没有涉及到转换问题
