### ISSUE TITLE
无法解析外部符号，ort1.16.2

### ISSUE THREAD

**Issue by YUANkkp** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#35]
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/91361441/df2bdafe-01c8-416e-9adb-845524d4bc44)

**Comment by YUANkkp** [comment]
改成13版本还是报这个错

**Comment by UNeedCryDear** [comment]
https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/issues/22
