### ISSUE TITLE
yolov8 obb官方旋转框出来了，希大佬更新一下代码

### ISSUE THREAD

**Issue by futureflsl** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#40]
yolov8 obb真是集成到ultralytics，希望大佬更新C++代码

**Comment by UNeedCryDear** [comment]
花了点时间弄下，其实就是将yolov8原本的多加一个通道，然后rect换成RotatedRect就可以了，你自己修改应该也花不了多少时间的

**Comment by UNeedCryDear** [comment]
@triple-Mu 并不是，这里的nms是RotatedRect，因为opencv对nms函数做了重载的操作，具体你可以看下opencv的dnn.hpp这个文件中的重载声明

![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/3b963cfe-bd60-4d5e-88be-60b54bab2982)

**Comment by triple-Mu** [comment]
> @triple-Mu 并不是，这里的nms是RotatedRect，因为opencv对nms函数做了重载的操作，具体你可以看下opencv的dnn.hpp这个文件中的重载声明
> 
> 
> 
> ![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/3b963cfe-bd60-4d5e-88be-60b54bab2982)
> 
> 

好的大佬，谢谢解答

**Comment by Taylover13** [comment]
旋转框怎么加关键点检测？

**Comment by UNeedCryDear** [comment]
> 旋转框怎么加关键点检测？

没有这个玩意吧，kpt是人体姿态的，要旋转框干嘛，还是你自己实现的？

**Comment by Taylover13** [comment]
我自己想实现的，不知道怎么搞。kpt的框能去掉吗？只预测点不要边界框
