### ISSUE TITLE
使用vs2022，创建的控制台应用程序，生成解决方案成功，应用程序无法正常启动(0xc000007b)，请问是缺少一些依赖库吗？

### ISSUE THREAD

**Issue by 1244547821** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#46]

**Comment by UNeedCryDear** [comment]
0xc000007b 这个问题一般是win10的C:/Windows/system32这个路径下面和C:\Windows\SysWOW64路径下面会自带有onnxruntime.dll这个东西，需要手动删除掉才行，不然由于索引的时候这目录优先级比环境变量的路径优先级高，导致找到的是这个dll就会报错。
至于删除，由于权限问题，会比较麻烦，需要手动先修改权限所有者，改到当前用户之后才可以删除。如果你不会改或者嫌弃麻烦，最好的解决方案是将onnxruntime的相关dll拷贝到你的exe路径下面去就可以正常运行了。
