### ISSUE TITLE
请问这个函数是做什么用的啊。。我自己写的跟你的流程就差这个函数，同样用bus.jpg测试就是不成功

### ISSUE THREAD

**Issue by krrqiw356** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#5]
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/95893b16ff5953514d69232341b8907ffc02b33d/yolov8_utils.cpp#L14

**Comment by UNeedCryDear** [comment]
自适应缩放图片的函数啊，将你原来的图片缩放到网络检测大小，跟python下面的是一样的功能

**Comment by UNeedCryDear** [comment]
cv::Vec4d& params
测试不成功是这个参数不对，这个是个长度为4的数组0~3下标分别表示 原图变换到检测图的时候XY缩放系数，原图在缩放之后左上角在检测图中的偏移量left和top
