### ISSUE TITLE
请问关于源码内容的一些问题

### ISSUE THREAD

**Issue by Rainer-seventeen** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#51]
你好！
_access()函数未定义，请问这是什么原因？我没有办法解决
因为不影响主要功能所以我注释掉了。
![截图 2024-04-08 21-18-19](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/56306642/a11b7628-fd12-44b8-ac21-f92173e2b4f2)

还有是头文件<io.h>路径需要改成<sys/io.h>才能找得到
（我的系统是Ubuntu22.04LTS）
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/56306642/fc977907-888c-4660-ae1c-e2aa65e9417d)

**Comment by UNeedCryDear** [comment]
无影响，这个是判断文件是否存在的，主要之前太多人路径设置不对导致报错，所以我加了这个更好的提示由于路径问题导致的运行错误。
linux下面我没怎么测试，你可以改成你自己的功能都ok，或者去掉相关的函数也是可以的，只要能保证文件路径对就ok
