### ISSUE TITLE
onnx-seg推理结果与官方ultralytics的python推理结果不一致

### ISSUE THREAD

**Issue by Zachhob** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#54]
你好，很高兴你能开源代码。我使用onnx推理yolov8-seg自训练模型，使用官方例子python推理的结果很好，但是使用C++推理效果非常差，图片和模型都是一致的，请问你有什么思路和建议吗？

**Comment by UNeedCryDear** [comment]
如果方便的话，请提供一下图片和pt模型，这个需要具体分析

**Comment by Zachhob** [comment]
可以的，那我把图片和pt还有onnx都发一份

**Comment by Zachhob** [comment]
这里是相关的内容

**Comment by Zachhob** [comment]
文件太大了，我发您邮箱可以吗

**Comment by Zachhob** [comment]
[Uploading 2_UNeedCryDear.zip…]()

**Comment by UNeedCryDear** [comment]
随便找个网盘啥的发吧，google或者BD或者腾讯甚至夸克啥的

**Comment by Zachhob** [comment]
链接: https://pan.baidu.com/s/1mLhrYveQndZBKlR40OZsfw 提取码: y63x

**Comment by UNeedCryDear** [comment]
你的onnx导出是1x3x480x640,所以你需要修改对应头文件里面的_netHeight为480，这里的设置默认为640.
![image](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/assets/52729998/d9268cbc-2c73-419b-9113-1b09528ab68d)

**Comment by Zachhob** [comment]
THX so much~问题解决了，感谢大佬。
