### ISSUE TITLE
rtdetr OnnxBatchDetect  多张图返回结果有问题

### ISSUE THREAD

**Issue by 1179993113** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#56]
rtdetr OnnxBatchDetect  多张图返回结果有问题，请问下改如何修改

**Comment by UNeedCryDear** [comment]
请给出具体问题说明，或者给出模型和测试图片，你这么说我也不清楚你到底结果问题是什么

**Comment by 1179993113** [comment]
第一张图片返回结果正常，后续的图片返回结果都有问题，猜测是不是 all_data += one_output_length导致的，因为其他检测的这行代码cv::Mat output0 = cv::Mat(cv::Size((int)_outputTensorShape[2], (int)_outputTensorShape[1]), CV_32F, all_data).t();  //[bs,116,8400]=>[bs,8400,116]    都进行过了.t()转置处理，redetr没有转置，从而导致后续的图片返回结果有异常？还请大佬帮忙解答一下，该如何修改
