### ISSUE TITLE
Error while compiling  "fatal error: onnxruntime_cxx_api.h: No such file or directory"

### ISSUE THREAD

**Issue by madinwei** [UNeedCryDear/yolov8-opencv-onnxruntime-cpp#8]
Hello 你好@UNeedCryDear , 

thank you for this amazing repository. While I was compiling I encountered the following ERROR:

```bash
$ make
[ 14%] Building CXX object CMakeFiles/YOLOv8.dir/main.cpp.o
In file included from /home/mad/yolov8-opencv-onnxruntime-cpp/main.cpp:6:0:
/home/mad/yolov8-opencv-onnxruntime-cpp/yolov8_onnx.h:6:32: fatal error: onnxruntime_cxx_api.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/YOLOv8.dir/build.make:76: CMakeFiles/YOLOv8.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/YOLOv8.dir/all] Error 2
```
To my knowledge, the error means that the Onnx lib is not installed, however, I have already installed it by downloading onnxruntime-linux-x64-gpu-1.9.0.tgz and unzip it in the /usr/local folder. 

I am still novice, so any help or advice will be valuable for me. looking forward to your response

**Comment by UNeedCryDear** [comment]
> 1. 编译后只生产 yolov8，我需要 yolov8-seg 有没有办法编译它？
> 2. 有没有办法在不需要编译的情况下使用C++代码？因为你不擅长 ^_^

1. https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/4b90bf0c3d86d67faf1a3683ccace79163b7c16d/CMakeLists.txt#L10

项目名字叫yolov8，实际上包括了yolov8和yolov8-seg，这两者又分别包括了opencv和onnxruntime两个版本。你可以通过修改这里的链接只编译其中一种组合（例如yolov8+onnxruntime），然后修改mian.cpp中的调用为yolov8+onnxruntime的调用，最后重新编译。
3. 不编译情况无法使用，c++本身就是编译型语言，不像python为解释型语言可以不编译使用。
